// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace LibFirewall
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "lib_firewall_rust";





        [DllImport(__DllName, EntryPoint = "firewall_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_init();

        [DllImport(__DllName, EntryPoint = "firewall_get_inbound_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern InboundRule* firewall_get_inbound_rules(int* count);

        [DllImport(__DllName, EntryPoint = "firewall_get_outbound_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern OutboundRule* firewall_get_outbound_rules(int* count);

        [DllImport(__DllName, EntryPoint = "firewall_get_connection_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ConnectionRule* firewall_get_connection_rules(int* count);

        [DllImport(__DllName, EntryPoint = "firewall_add_inbound_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_add_inbound_rule(InboundRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_add_outbound_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_add_outbound_rule(OutboundRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_update_inbound_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_update_inbound_rule(InboundRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_update_outbound_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_update_outbound_rule(OutboundRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_delete_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_delete_rule(byte* name);

        [DllImport(__DllName, EntryPoint = "firewall_add_connection_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_add_connection_rule(ConnectionRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_update_connection_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_update_connection_rule(ConnectionRule* rule);

        [DllImport(__DllName, EntryPoint = "firewall_delete_connection_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool firewall_delete_connection_rule(byte* name);

        [DllImport(__DllName, EntryPoint = "firewall_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void firewall_free_string(byte* ptr);

        [DllImport(__DllName, EntryPoint = "firewall_free_inbound_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void firewall_free_inbound_rules(InboundRule* ptr, int len);

        [DllImport(__DllName, EntryPoint = "firewall_free_outbound_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void firewall_free_outbound_rules(OutboundRule* ptr, int len);

        [DllImport(__DllName, EntryPoint = "firewall_free_connection_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void firewall_free_connection_rules(ConnectionRule* ptr, int len);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct InboundRule
    {
        public byte* name;
        public byte* description;
        public RuleDirection direction;
        public RuleAction action;
        [MarshalAs(UnmanagedType.U1)] public bool enabled;
        public int protocol;
        public byte* local_ports;
        public byte* remote_ports;
        public byte* local_addresses;
        public byte* remote_addresses;
        public int profiles;
        public byte* interface_types;
        [MarshalAs(UnmanagedType.U1)] public bool edge_traversal;
        public byte* local_user_authorized_list;
        public byte* remote_user_authorized_list;
        public byte* remote_machine_authorized_list;
        public byte* application_name;
        public byte* service_name;
        public byte* grouping;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct OutboundRule
    {
        public byte* name;
        public byte* description;
        public RuleDirection direction;
        public RuleAction action;
        [MarshalAs(UnmanagedType.U1)] public bool enabled;
        public int protocol;
        public byte* local_ports;
        public byte* remote_ports;
        public byte* local_addresses;
        public byte* remote_addresses;
        public int profiles;
        public byte* interface_types;
        [MarshalAs(UnmanagedType.U1)] public bool edge_traversal;
        public byte* local_user_authorized_list;
        public byte* remote_user_authorized_list;
        public byte* remote_machine_authorized_list;
        public byte* application_name;
        public byte* service_name;
        public byte* grouping;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ConnectionRule
    {
        public byte* name;
        public byte* description;
        public ConnectionSecurityRuleType rule_type;
        [MarshalAs(UnmanagedType.U1)] public bool enabled;
        public int profiles;
        public byte* local_addresses;
        public byte* remote_addresses;
        public byte* endpoint1_ports;
        public byte* endpoint2_ports;
        public int protocol;
        public int auth_type;
    }


    public enum RuleDirection : uint
    {
        Inbound = 1,
        Outbound = 2,
    }

    public enum RuleAction : uint
    {
        Block = 0,
        Allow = 1,
    }

    public enum ConnectionSecurityRuleType : uint
    {
        Isolation = 1,
        AuthenticationExemption = 2,
        ServerToServer = 3,
        Tunnel = 4,
        Custom = 5,
    }


}
