// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace LibFirewall
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "lib_firewall_rust";





        [DllImport(__DllName, EntryPoint = "rust_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int rust_add(int a, int b);


    }



}
